runtime: php74

env: standard
instance_class: F1

includes:
  - secret.yaml

handlers:
  - url: /css
    static_dir: css
    secure: always

  - url: /js
    static_dir: js
    secure: always

  - url: /image
    static_dir: image
    secure: always

  - url: /posts
    static_dir: posts
    secure: always

  - url: /
    script: index.php
    secure: always

  - url: /php/send_form
    script: php/send_form.php
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80