name: Deploy to GCP

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: decode secret.yaml
        env:
          BASE64_SECRET: ${{ secrets.BASE64_SECRET_ENV }}
        run: echo -n $BASE64_SECRET_ENV | base64 --decode > ~/secret.yaml

      - name: Deploy an App Engine app
        uses: google-github-actions/deploy-appengine@v0.8.2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml secret.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1