name: Deploy to GCP

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: decode secret.yaml
        env:
          BASE64_SECRET_ENV: ${{ secrets.BASE64_SECRET_ENV }}
        run: echo -n $BASE64_SECRET_ENV | base64 --decode > secret.yaml

      - name: auth to GCP
        uses: google-github-actions/auth@v0.8.2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: deploy an App Engine
        uses: google-github-actions/deploy-appengine@v0.8.2